---
apiVersion: v1
kind: Template
metadata:
  name: front-end-template
  annotations:
   description: "A template to deploy the front-end for Sock-Shop."
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: front-end
  spec:
    replicas: 1
    selector:
      name: front-end
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: front-end
      spec:
        containers:
        - image: 172.30.1.1:5000/${PROJECT_NAMESPACE}/front-end
          name: front-end
          ports:
          - containerPort: 8079
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - front-end
        from:
          kind: ImageStreamTag
          name: "front-end:${PROJECT_NAMESPACE}"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: front-end
    labels:
      name: front-end
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 8079
      nodePort: ${NODE_PORT}
    selector:
      name: front-end
parameters:
- description: project namespace
  name: PROJECT_NAMESPACE
  required: true
- description: project namespace
  name: NODE_PORT
  required: true
