apiVersion: "v1"
kind: "ImageStream"
metadata:
  name: queue-master
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: queue-master-build
spec:
  source:
    git:
      uri: "https://github.com/Liatrio-LOK/queue-master"
      ref: "master"
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: "DockerImage"
        name: "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift"
  output:
    to:
      kind: ImageStreamTag
      name: queue-master:latest
      namespace: sock-shop

