apiVersion: v1
kind: Service
metadata:
  name: front-end-blue
  labels:
    name: front-end-blue
  namespace: sock-shop
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30002
  selector:
    name: front-end-blue
