apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: hub
  name: hub
spec:
  ports:
  - name: 4444-tcp
    port: 4444
    protocol: TCP
    targetPort: 4444
    nodePort: 30002
  selector:
    app: hub
    deploymentconfig: hub
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
