#!/bin/bash

# create the jenkins project namespace and app
oc new-project jenkins
oc new-app jenkins-persistent --env MINISHIFT_IP=$(minishift ip)
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:jenkins:jenkins
oc login -u developer -p dev
oc create -f builds/front-end.yaml # buildConfig with imagestream and for building front-end image

oc delete project myproject

# create the selenium hub project
oc new-project selenium-hub
oc new-app --docker-image=selenium/hub:latest

# create the selenium node project
oc new-project selenium-nodes
oc new-app --docker-image=selenium/node-chrome:latest --env HUB_PORT_4444_TCP_ADDR="$(minishift ip)" HUB_PORT_4444_TCP_PORT="30002"
oc new-app --docker-image=selenium/node-firefox:latest --env HUB_PORT_4444_TCP_ADDR="$(minishift ip)" HUB_PORT_4444_TCP_PORT="30002"

# create the environments

oc new-project dev
oc create imagestream front-end
oc create -f templates/front-end.yml # deploymentConfig for front-end
oc new-app front-end-template -p PROJECT_NAMESPACE=dev -p NODE_PORT=30011

oc new-project prod
oc create imagestream front-end
oc create -f templates/front-end.yml # deploymentConfig for front-end
oc new-app front-end-template -p PROJECT_NAMESPACE=prod -p NODE_PORT=30014


#oc create -f microservices-demo/deploy/openshift/builds/front-end.yml buildConfig with imagestream and for building front-end image
# oc create -f microservices-demo/deploy/openshift/pipelines/front-end.yml look into this line for POC v2
